parameters:
- name: runPublicJobs
  type: boolean
  default: false
- name: runPrivateJobs
  type: boolean
  default: false
- name: runScheduledPrivateJobs
  type: boolean
  default: false
- name: onlySanityCheck
  type: boolean
  default: false

resources:
  containers:
    - container: ubuntu_x64_build_container
      image: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-22.04

trigger:
  branches:
    include:
    - main
  paths:
    exclude: # don't trigger if only docs and similar files changed
    - docs/*
    - '**/*.md'
    - 'gc-azure-pipelines.yml'
    - src/benchmarks/gc/*

pr:
  branches:
    include:
    - main
  paths:
    exclude: # don't trigger if only docs and similar files changed
    - docs/*
    - '**/*.md'
    - scripts/benchmarks_monthly.py
    - 'gc-azure-pipelines.yml'
    - src/benchmarks/gc/*

schedules:
- cron: "0 */12 * * *"
  displayName: Every 12 hours build
  branches:
    include:
    - main
  always: true
- cron: "0 21 * * THU"
  displayName: Weekly Build
  branches:
    include:
    - main
  always: true

jobs:
  # Test branch: run one configuration per mobile platform.
  - template: /eng/pipelines/templates/build-machine-matrix.yml
    parameters:
      jobTemplate: /eng/pipelines/templates/run-scenarios-job.yml
      buildMachines:
        - win-x64-android-arm64-pixel
      isPublic: false
      jobParameters:
        runKind: maui_scenarios_android
        projectFileName: maui_scenarios_android.proj
        channels:
          - main
        runtimeFlavor: coreclr
        codeGenType: Default
        buildConfig: Release
        additionalJobIdentifier: CoreCLR
        onlySanityCheck: ${{ parameters.onlySanityCheck }}

  - template: /eng/pipelines/templates/build-machine-matrix.yml
    parameters:
      jobTemplate: /eng/pipelines/templates/run-scenarios-job.yml
      buildMachines:
        - osx-x64-ios-arm64
      isPublic: false
      jobParameters:
        runKind: maui_scenarios_ios
        projectFileName: maui_scenarios_ios.proj
        channels:
          - main
        runtimeFlavor: coreclr
        codeGenType: Default
        buildConfig: Release
        additionalJobIdentifier: CoreCLR
        onlySanityCheck: ${{ parameters.onlySanityCheck }}
