parameters:
  buildMachines: []
  isPublic: true
  jobTemplate: ''
  jobParameters: {}

jobs:
- ${{ if containsValue(parameters.buildMachines, 'win-x64') }}:
  - template: ${{ parameters.jobTemplate }}
    parameters:
      osName: windows
      architecture: x64
      pool:
        vmImage: windows-2019
      ${{ insert }}: ${{ parameters.jobParameters }}
      ${{ if eq(parameters.isPublic, true) }}:
        osVersion: 22H2
        machinePool: Open
        queue: Windows.10.Amd64.Client.Open
      ${{ else }}:
        osVersion: 19H1
        machinePool: Tiger
        queue: Windows.10.Amd64.19H1.Tiger.Perf

- ${{ if and(containsValue(parameters.buildMachines, 'win-rs5-x64'), eq(parameters.isPublic, true)) }}: # RS5 only used in public builds currently
  - template: ${{ parameters.jobTemplate }}
    parameters:
      osName: windows
      osVersion: RS5
      architecture: x64
      pool:
        vmImage: windows-2019
      machinePool: Open
      queue: Windows.10.Amd64.ClientRS5.Open
      ${{ insert }}: ${{ parameters.jobParameters }}

- ${{ if containsValue(parameters.buildMachines, 'win-x86') }}:
  - template: ${{ parameters.jobTemplate }}
    parameters:
      osName: windows
      architecture: x86
      pool:
        vmImage: windows-2019
      ${{ insert }}: ${{ parameters.jobParameters }}
      ${{ if eq(parameters.isPublic, true) }}:
        osVersion: 22H2
        machinePool: Open
        queue: Windows.10.Amd64.Client.Open
      ${{ else }}:
        osVersion: 19H1
        machinePool: Tiger
        queue: Windows.10.Amd64.19H1.Tiger.Perf

- ${{ if containsValue(parameters.buildMachines, 'ubuntu-x64') }}:
  - template: ${{ parameters.jobTemplate }}
    parameters:
      osName: ubuntu
      osVersion: 2204
      architecture: x64
      pool: 
        vmImage: ubuntu-latest
      container: ubuntu_x64_build_container
      ${{ insert }}: ${{ parameters.jobParameters }}
      ${{ if eq(parameters.isPublic, true) }}:
        machinePool: Open
        queue: Ubuntu.2204.Amd64.Open
      ${{ else }}:
        machinePool: Tiger
        queue: Ubuntu.2204.Amd64.Tiger.Perf # using a dedicated private Helix queue (perftigers)

# While we wait for lttng updates on Ubuntu 22.04 we are going to use 18.04
- ${{ if containsValue(parameters.buildMachines, 'ubuntu-x64-1804') }}:
  - template: ${{ parameters.jobTemplate }}
    parameters:
      osName: ubuntu
      osVersion: 1804
      architecture: x64
      pool: 
        vmImage: ubuntu-latest
      container: ubuntu_x64_build_container
      ${{ insert }}: ${{ parameters.jobParameters }}
      ${{ if eq(parameters.isPublic, true) }}:
        machinePool: Open
        queue: Ubuntu.1804.Amd64.Open
      ${{ else }}:
        machinePool: Tiger
        queue: Ubuntu.1804.Amd64.Tiger.Perf # using a dedicated private Helix queue (perftigers)

- ${{ if and(containsValue(parameters.buildMachines, 'win-arm64'), not(eq(parameters.isPublic, true))) }}: # Windows ARM64 only used in private builds currently
  - template: ${{ parameters.jobTemplate }}
    parameters:
      osName: windows
      osVersion: 20H1
      architecture: arm64
      pool:
        vmImage: windows-2019
      machinePool: Tiger
      queue: Windows.10.Arm64.Perf.Surf
      ${{ insert }}: ${{ parameters.jobParameters }}

- ${{ if and(containsValue(parameters.buildMachines, 'win-arm64-ampere'), not(eq(parameters.isPublic, true))) }}: # Windows ARM64 only used in private builds currently
  - template: ${{ parameters.jobTemplate }}
    parameters:
      osName: windows
      osVersion: 22H2
      architecture: arm64
      pool:
        vmImage: windows-2019
      machinePool: Ampere
      queue: Windows.Server.Arm64.Perf
      ${{ insert }}: ${{ parameters.jobParameters }}

- ${{ if and(containsValue(parameters.buildMachines, 'ubuntu-arm64-ampere'), not(eq(parameters.isPublic, true))) }}: # Ubuntu ARM64 only used in private builds currently
  - template: ${{ parameters.jobTemplate }}
    parameters:
      osName: ubuntu
      osVersion: 2004
      architecture: arm64
      pool:
        vmImage: ubuntu-20.04
      machinePool: Ampere
      queue: Ubuntu.2004.Arm64.Perf
      ${{ insert }}: ${{ parameters.jobParameters }}

- ${{ if and(containsValue(parameters.buildMachines, 'win-x64-android-arm64-pixel'), not(eq(parameters.isPublic, true))) }}: # Windows ARM64 Pixel only used in private builds currently
  - template: ${{ parameters.jobTemplate }}
    parameters:
      osName: windows
      architecture: x64
      osVersion: 19H1
      pool:
        vmImage: 'windows-2022'
      queue: Windows.10.Amd64.Pixel.Perf
      machinePool: Pixel
      ${{ insert }}: ${{ parameters.jobParameters }}

- ${{ if and(containsValue(parameters.buildMachines, 'win-x64-android-arm64-galaxy'), not(eq(parameters.isPublic, true))) }}: # Windows ARM64 Galaxy only used in private builds currently
  - template: ${{ parameters.jobTemplate }}
    parameters:
      osName: windows
      architecture: x64
      osVersion: 19H1
      pool:
        vmImage: 'windows-2022'
      queue: Windows.10.Amd64.Galaxy.Perf
      machinePool: Galaxy
      ${{ insert }}: ${{ parameters.jobParameters }}

- ${{ if and(containsValue(parameters.buildMachines, 'osx-x64-ios-arm64'), not(eq(parameters.isPublic, true))) }}: # iPhone ARM64 12mini only used in private builds currently
  - template: ${{ parameters.jobTemplate }}
    parameters:
      osName: osx
      architecture: x64
      osVersion: 12
      pool:
        vmImage: 'macos-12'
      queue: OSX.1015.Amd64.Iphone.Perf
      machinePool: iPhoneMini12
      ${{ insert }}: ${{ parameters.jobParameters }}
