resources:
  containers:
    - container: ubuntu_x64_build_container
      image: microsoft/dotnet-buildtools-prereqs:ubuntu-16.04-c103199-20180628134544

trigger: none

pr: none

jobs:

# Windows x64 micro benchmarks, public correctness job
- ${{ if eq(variables['System.TeamProject'], 'public') }}:
  - template: /eng/performance/benchmark_jobs.yml
    parameters:
      osName: windows
      osVersion: RS4
      kind: micro
      architecture: x64
      pool: Hosted VS2017
      queue: Windows.10.Amd64.ClientRS4.Open
      csproj: src\benchmarks\micro\MicroBenchmarks.csproj
      runCategories: 'coreclr corefx' 
      frameworks: # for public jobs we want to make sure that the PRs don't break any of the supported frameworks
        - netcoreapp3.0

# Windows x86 micro benchmarks, public correctness job
- ${{ if eq(variables['System.TeamProject'], 'public') }}:
  - template: /eng/performance/benchmark_jobs.yml
    parameters:
      osName: windows
      osVersion: RS4
      kind: micro
      architecture: x86
      pool: Hosted VS2017
      queue: Windows.10.Amd64.ClientRS4.Open
      csproj: src\benchmarks\micro\MicroBenchmarks.csproj
      runCategories: 'coreclr corefx'
      frameworks: # for public jobs we want to make sure that the PRs don't break x86
        - netcoreapp3.0
        
# Ubuntu 1604 x64 micro benchmarks, public correctness job
- ${{ if eq(variables['System.TeamProject'], 'public') }}:
  - template: /eng/performance/benchmark_jobs.yml
    parameters:
      osName: ubuntu
      osVersion: 1604
      kind: micro
      architecture: x64
      pool: Hosted Ubuntu 1604
      queue: Ubuntu.1604.Amd64.Open
      container: ubuntu_x64_build_container
      csproj: src/benchmarks/micro/MicroBenchmarks.csproj
      runCategories: 'coreclr corefx'
      frameworks: # for public jobs we want to make sure that the PRs don't break any of the supported frameworks
        - netcoreapp3.0

# Windows x64 ML.NET benchmarks, public correctness job
- ${{ if eq(variables['System.TeamProject'], 'public') }}:
  - template: /eng/performance/benchmark_jobs.yml
    parameters:
      osName: windows
      osVersion: RS4
      kind: mlnet
      architecture: x64
      pool: Hosted VS2017
      queue: Windows.10.Amd64.ClientRS4.Open
      csproj: src\benchmarks\real-world\Microsoft.ML.Benchmarks\Microsoft.ML.Benchmarks.csproj
      runCategories: 'mldotnet'
      frameworks: # for ML.NET jobs we want to check .NET Core 3.0 only
        - netcoreapp3.0

# Ubuntu 1604 x64 ML.NET benchmarks, public correctness job
- ${{ if eq(variables['System.TeamProject'], 'public') }}:
  - template: /eng/performance/benchmark_jobs.yml
    parameters:
      osName: ubuntu
      osVersion: 1604
      kind: mlnet
      architecture: x64
      pool: Hosted Ubuntu 1604
      queue: Ubuntu.1604.Amd64.Open
      container: ubuntu_x64_build_container
      runCategories: 'mldotnet'
      csproj: src/benchmarks/real-world/Microsoft.ML.Benchmarks/Microsoft.ML.Benchmarks.csproj
      frameworks: # for ML.NET jobs we want to check .NET Core 3.0 only
        - netcoreapp3.0

# Windows x64 Roslyn benchmarks, public correctness job
- ${{ if eq(variables['System.TeamProject'], 'public') }}:
  - template: /eng/performance/benchmark_jobs.yml
    parameters:
      osName: windows
      osVersion: RS4
      kind: roslyn
      architecture: x64
      pool: Hosted VS2017
      queue: Windows.10.Amd64.ClientRS4.Open
      csproj: src\benchmarks\real-world\Roslyn\CompilerBenchmarks.csproj
      runCategories: 'roslyn'
      frameworks: # for Roslyn jobs we want to check .NET Core 3.0 only
        - netcoreapp3.0

# Ubuntu 1604 x64 Roslyn benchmarks, public correctness job
- ${{ if eq(variables['System.TeamProject'], 'public') }}:
  - template: /eng/performance/benchmark_jobs.yml
    parameters:
      osName: ubuntu
      osVersion: 1604
      kind: roslyn
      architecture: x64
      pool: Hosted Ubuntu 1604
      queue: Ubuntu.1604.Amd64.Open
      container: ubuntu_x64_build_container
      runCategories: 'roslyn'
      csproj: src/benchmarks/real-world/Roslyn/CompilerBenchmarks.csproj
      frameworks: # for Roslyn jobs we want to check .NET Core 3.0 only
        - netcoreapp3.0
        