<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <!-- This repo version -->
    <VersionPrefix>1.0.0</VersionPrefix>
    <PreReleaseVersionLabel>beta</PreReleaseVersionLabel>
  </PropertyGroup>
  <!--Package versions-->
  <PropertyGroup>
    <MicrosoftNETILLinkTasksVersion>11.0.0-rc.1.26411.119</MicrosoftNETILLinkTasksVersion>
    <MicrosoftNETILLinkPackageVersion>11.0.0-rc.1.26411.119</MicrosoftNETILLinkPackageVersion>
    <SystemThreadingChannelsPackageVersion>11.0.0-rc.1.26411.119</SystemThreadingChannelsPackageVersion>
    <MicrosoftExtensionsLoggingPackageVersion>11.0.0-rc.1.26411.119</MicrosoftExtensionsLoggingPackageVersion>
    <BenchmarkDotNetVersion>0.16.0-nightly.20260801.595</BenchmarkDotNetVersion>
    <MicrosoftNETRuntimeEmscripten3156Nodewinx64Version>11.0.0-preview.5.26261.101</MicrosoftNETRuntimeEmscripten3156Nodewinx64Version>
    <MicrosoftDotNetXHarnessCLIVersion>11.0.0-prerelease.26411.5</MicrosoftDotNetXHarnessCLIVersion>
  </PropertyGroup>
  <!--Package names-->
  <PropertyGroup>
  </PropertyGroup>
</Project>
