parameters:
  - name: perfBranch # Currently only used for building the BDN App
    type: string
    default: main
  - name: jobParameters
    type: object
    default: {}
  - name: runtimeRepoAlias
    type: string
    default: runtime
  - name: performanceRepoAlias
    type: string
    default: self
  - name: crossgen
    type: object
    default:
      enabled: true
      configs:
        - windows_x64
        - windows_x86
  - name: viperJitOptRepeat
    type: object
    default:
      enabled: true
      configs:
        - windows_x64
        - linux_x64
  - name: viperMicro
    type: object
    default:
      enabled: true
      configs:
        - windows_x64
        - linux_x64
  - name: owlMicro
    type: object
    default:
      enabled: true
      configs:
        - windows_x64
        - linux_x64
  - name: tigerMicro
    type: object
    default:
      enabled: true
      configs:
        - windows_x64
        - linux_x64
  - name: androidMono
    type: object
    default:
      enabled: true
      configs:
        - android_arm64

jobs:
  - template: /eng/pipelines/performance/templates/perf-build-jobs.yml@${{ parameters.runtimeRepoAlias }}
    parameters:
      perfBranch: ${{ parameters.perfBranch }}

  # Build and run iOS Mono and NativeAOT scenarios
  - template: /eng/pipelines/runtime-ios-scenarios-perf-jobs.yml
    parameters:
      hybridGlobalization: True
      runtimeRepoAlias: ${{ parameters.runtimeRepoAlias }}
      performanceRepoAlias: ${{ parameters.performanceRepoAlias }}
      jobParameters: ${{ parameters.jobParameters }}

  # run android scenarios - Mono JIT
  - template: /eng/pipelines/common/platform-matrix.yml@${{ parameters.runtimeRepoAlias }}
    parameters:
      jobTemplate: /eng/pipelines/templates/runtime-perf-job.yml@${{ parameters.performanceRepoAlias }}
      buildConfig: release
      runtimeFlavor: mono
      platforms:
        - windows_x64
      jobParameters:
        runtimeType: AndroidMono
        codeGenType: JIT
        projectFile: $(Build.SourcesDirectory)/eng/testing/performance/android_scenarios.proj
        runKind: android_scenarios
        isScenario: true
        logicalMachine: 'perfpixel4a'
        runtimeRepoAlias: ${{ parameters.runtimeRepoAlias }}
        performanceRepoAlias: ${{ parameters.performanceRepoAlias }}
        ${{ each parameter in parameters.jobParameters }}:
          ${{ parameter.key }}: ${{ parameter.value }}

  # run android scenarios - Mono AOT
  - template: /eng/pipelines/common/platform-matrix.yml@${{ parameters.runtimeRepoAlias }}
    parameters:
      jobTemplate: /eng/pipelines/templates/runtime-perf-job.yml@${{ parameters.performanceRepoAlias }}
      buildConfig: release
      runtimeFlavor: mono
      platforms:
        - windows_x64
      jobParameters:
        runtimeType: AndroidMono
        codeGenType: AOT
        projectFile: $(Build.SourcesDirectory)/eng/testing/performance/android_scenarios.proj
        runKind: android_scenarios
        isScenario: true
        logicalMachine: 'perfpixel4a'
        runtimeRepoAlias: ${{ parameters.runtimeRepoAlias }}
        performanceRepoAlias: ${{ parameters.performanceRepoAlias }}
        ${{ each parameter in parameters.jobParameters }}:
          ${{ parameter.key }}: ${{ parameter.value }}

  # run android scenarios - CoreCLR JIT
  - template: /eng/pipelines/common/platform-matrix.yml@${{ parameters.runtimeRepoAlias }}
    parameters:
      jobTemplate: /eng/pipelines/templates/runtime-perf-job.yml@${{ parameters.performanceRepoAlias }}
      buildConfig: release
      runtimeFlavor: coreclr
      platforms:
        - windows_x64
      jobParameters:
        runtimeType: AndroidCoreCLR
        codeGenType: JIT
        projectFile: $(Build.SourcesDirectory)/eng/testing/performance/android_scenarios.proj
        runKind: android_scenarios
        isScenario: true
        logicalMachine: 'perfpixel4a'
        runtimeRepoAlias: ${{ parameters.runtimeRepoAlias }}
        performanceRepoAlias: ${{ parameters.performanceRepoAlias }}
        ${{ each parameter in parameters.jobParameters }}:
          ${{ parameter.key }}: ${{ parameter.value }}

  # run android scenarios - CoreCLR JIT Static Linking
  - template: /eng/pipelines/common/platform-matrix.yml@${{ parameters.runtimeRepoAlias }}
    parameters:
      jobTemplate: /eng/pipelines/templates/runtime-perf-job.yml@${{ parameters.performanceRepoAlias }}
      buildConfig: release
      runtimeFlavor: coreclr
      platforms:
        - windows_x64
      jobParameters:
        runtimeType: AndroidCoreCLR
        codeGenType: JIT
        linkingType: static
        projectFile: $(Build.SourcesDirectory)/eng/testing/performance/android_scenarios.proj
        runKind: android_scenarios
        isScenario: true
        logicalMachine: 'perfpixel4a'
        runtimeRepoAlias: ${{ parameters.runtimeRepoAlias }}
        performanceRepoAlias: ${{ parameters.performanceRepoAlias }}
        ${{ each parameter in parameters.jobParameters }}:
          ${{ parameter.key }}: ${{ parameter.value }}

  # run android scenarios - CoreCLR R2R
  - template: /eng/pipelines/common/platform-matrix.yml@${{ parameters.runtimeRepoAlias }}
    parameters:
      jobTemplate: /eng/pipelines/templates/runtime-perf-job.yml@${{ parameters.performanceRepoAlias }}
      buildConfig: release
      runtimeFlavor: coreclr
      platforms:
        - windows_x64
      jobParameters:
        runtimeType: AndroidCoreCLR
        codeGenType: R2R
        projectFile: $(Build.SourcesDirectory)/eng/testing/performance/android_scenarios.proj
        runKind: android_scenarios
        isScenario: true
        logicalMachine: 'perfpixel4a'
        runtimeRepoAlias: ${{ parameters.runtimeRepoAlias }}
        performanceRepoAlias: ${{ parameters.performanceRepoAlias }}
        ${{ each parameter in parameters.jobParameters }}:
          ${{ parameter.key }}: ${{ parameter.value }}

  # run mono microbenchmarks perf job
  - template: /eng/pipelines/common/platform-matrix.yml@${{ parameters.runtimeRepoAlias }}
    parameters:
      jobTemplate: /eng/pipelines/templates/runtime-perf-job.yml@${{ parameters.performanceRepoAlias }}
      buildConfig: release
      runtimeFlavor: mono
      platforms:
      - linux_x64
      jobParameters:
        liveLibrariesBuildConfig: Release
        runtimeType: mono
        runKind: micro_mono
        logicalMachine: 'perfviper'
        runtimeRepoAlias: ${{ parameters.runtimeRepoAlias }}
        performanceRepoAlias: ${{ parameters.performanceRepoAlias }}
        ${{ each parameter in parameters.jobParameters }}:
          ${{ parameter.key }}: ${{ parameter.value }}


  # run mono interpreter perf job
  - template: /eng/pipelines/common/platform-matrix.yml@${{ parameters.runtimeRepoAlias }}
    parameters:
      jobTemplate: /eng/pipelines/templates/runtime-perf-job.yml@${{ parameters.performanceRepoAlias }}
      buildConfig: release
      runtimeFlavor: mono
      platforms:
      - linux_x64
      jobParameters:
        liveLibrariesBuildConfig: Release
        runtimeType: mono
        codeGenType: 'Interpreter'
        runKind: micro_mono
        logicalMachine: 'perfviper'
        runtimeRepoAlias: ${{ parameters.runtimeRepoAlias }}
        performanceRepoAlias: ${{ parameters.performanceRepoAlias }}
        ${{ each parameter in parameters.jobParameters }}:
          ${{ parameter.key }}: ${{ parameter.value }}

  # run mono aot microbenchmarks perf job
  - template: /eng/pipelines/common/platform-matrix.yml@${{ parameters.runtimeRepoAlias }}
    parameters:
      jobTemplate: /eng/pipelines/templates/runtime-perf-job.yml@${{ parameters.performanceRepoAlias }}
      buildConfig: release
      runtimeFlavor: aot
      platforms:
      - linux_x64
      jobParameters:
        liveLibrariesBuildConfig: Release
        runtimeType: mono
        codeGenType: 'AOT'
        runKind: micro_mono
        logicalMachine: 'perfviper'
        runtimeRepoAlias: ${{ parameters.runtimeRepoAlias }}
        performanceRepoAlias: ${{ parameters.performanceRepoAlias }}
        ${{ each parameter in parameters.jobParameters }}:
          ${{ parameter.key }}: ${{ parameter.value }}

  # run coreclr perftiger microbenchmarks perf job
  - template: /eng/pipelines/common/platform-matrix.yml@${{ parameters.runtimeRepoAlias }}
    parameters:
      jobTemplate: /eng/pipelines/templates/runtime-perf-job.yml@${{ parameters.performanceRepoAlias }}
      buildConfig: release
      runtimeFlavor: coreclr
      platforms:
      - linux_x64
      - windows_x64
      jobParameters:
        liveLibrariesBuildConfig: Release
        runKind: micro
        logicalMachine: 'perftiger'
        runtimeRepoAlias: ${{ parameters.runtimeRepoAlias }}
        performanceRepoAlias: ${{ parameters.performanceRepoAlias }}
        ${{ each parameter in parameters.jobParameters }}:
          ${{ parameter.key }}: ${{ parameter.value }}

  # run coreclr perfviper microbenchmarks perf job
  - template: /eng/pipelines/common/platform-matrix.yml@${{ parameters.runtimeRepoAlias }}
    parameters:
      jobTemplate: /eng/pipelines/templates/runtime-perf-job.yml@${{ parameters.performanceRepoAlias }}
      buildConfig: release
      runtimeFlavor: coreclr
      platforms:
      - linux_x64
      - windows_x64
      - windows_x86
      jobParameters:
        liveLibrariesBuildConfig: Release
        runKind: micro
        logicalMachine: 'perfviper'
        runtimeRepoAlias: ${{ parameters.runtimeRepoAlias }}
        performanceRepoAlias: ${{ parameters.performanceRepoAlias }}
        ${{ each parameter in parameters.jobParameters }}:
          ${{ parameter.key }}: ${{ parameter.value }}

  # run coreclr perfviper microbenchmarks perf job with NoR2R
  - template: /eng/pipelines/common/platform-matrix.yml@${{ parameters.runtimeRepoAlias }}
    parameters:
      jobTemplate: /eng/pipelines/templates/runtime-perf-job.yml@${{ parameters.performanceRepoAlias }}
      buildConfig: release
      runtimeFlavor: coreclr
      platforms:
      - linux_x64
      - windows_x64
      jobParameters:
        liveLibrariesBuildConfig: Release
        runKind: micro
        logicalMachine: 'perfviper'
        runtimeRepoAlias: ${{ parameters.runtimeRepoAlias }}
        performanceRepoAlias: ${{ parameters.performanceRepoAlias }}
        r2rRunType: nor2r
        additionalJobIdentifier: 'NoR2R'
        ${{ each parameter in parameters.jobParameters }}:
          ${{ parameter.key }}: ${{ parameter.value }}

  # run coreclr crossgen perf job
  - ${{ if false }}: # Disabling as all crossgen jobs are failing at the moment - https://github.com/dotnet/performance/issues/4819
    - template: /eng/pipelines/common/platform-matrix.yml@${{ parameters.runtimeRepoAlias }}
      parameters:
        jobTemplate: /eng/pipelines/templates/runtime-perf-job.yml@${{ parameters.performanceRepoAlias }}
        buildConfig: release
        runtimeFlavor: coreclr
        platforms:
        - windows_x64
        - windows_x86
        jobParameters:
          liveLibrariesBuildConfig: Release
          projectFile: $(Build.SourcesDirectory)/eng/testing/performance/crossgen_perf.proj
          runKind: crossgen_scenarios
          isScenario: true
          logicalMachine: 'perftiger_crossgen' # Update when re-enabling as PerfTiger is now fewer machines (or completely decommissioned)
          runtimeRepoAlias: ${{ parameters.runtimeRepoAlias }}
          performanceRepoAlias: ${{ parameters.performanceRepoAlias }}
          ${{ each parameter in parameters.jobParameters }}:
            ${{ parameter.key }}: ${{ parameter.value }}
