//  <auto-generated >
//    <Generated by the FSharp WriteCodeFragment class./>
//  </auto-generated/>
//
module internal FSharp.BuildProperties
let fsProductVersion = "12.0.4.0"
let fsLanguageVersion = "6.0"
