parameters:
  buildType: ''
  buildId: ''

jobs:
  - job: RegisterBuild_${{ parameters.buildType }}
    displayName: 'Register Build (${{ parameters.buildType }})'
    steps:
    - checkout: none
    - task: AzureCLI@2
      displayName: 'Upload build info file'
      inputs:
        azureSubscription: '.NET Performance (790c4451-dad9-4fda-af8b-10bd9ca328fa)'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az storage blob upload --auth-mode login --account-name pvscmdupload --container-name builds --data '{"buildId":"${{ parameters.buildId }}"}' --name "buildArtifacts/${{ variables['Build.SourceVersion'] }}/${{ parameters.buildType }}/buildInfo.json" --overwrite true
